FROM tensorflow/tensorflow:latest-gpu-py3-jupyter
MAINTAINER LunchPlay
ADD requirements.txt .
RUN pip install --upgrade pip
RUN pip install Kaggler
RUN mkdir /tf/LunchPlay
RUN chmod 777 /tf/LunchPlay

